### ISSUE TITLE
Extracting MPNN/mol encoder for auxilary task

### ISSUE THREAD

**Issue by seyonechithrananda** [dmis-lab/PerceiverCPI#2]
Hi @NathanielNguyen11,

Really enjoyed reading the paper on a cross-attention based protein-ligand model. I was wondering if you had any pointers regarding how to best go about extracting the MPNN/mol encoder portion of the model for training on a downstream task (i.e - multi-task prediction; not another protein-ligand binding task). I was hoping to use fine-tune the mol encoder trained on my protein-ligand dataset on a downstream dataset which could benefit from the prior dataset I have trained it on using Perceiver.

Thanks for your help,
Seyone

**Comment by quangnguyenbn99** [comment]
Hi @seyonechithrananda ,
First of all, thank you very much for your attention to our work.
Addressing your question precisely proves challenging due to the intricacies involved in the freeze and unfreeze technique, particularly concerning the size of the pretrain and fine-tune dataset. Nevertheless, while the significance of individual layers might not be fully discernible, I highly recommend you freeze the model following its depth.
Wish you have a fantastic day there,

**Comment by quangnguyenbn99** [comment]
Feel free to inform me of any other issues you discover or feature requests that come to mind in the future. Pull Requests (PRs) are also always welcomed!
